site_name: "Riven"
site_description: "Riven is a media manager service that handles all your media needs."
site_author: "Riven Media"
site_url: "https://rivenmedia.github.io/wiki"

repo_name: "rivenmedia/riven"
repo_url: "https://github.com/rivenmedia/riven"

nav:
  - Home: index.md
  - Services:
    - General: services/index.md
    - Content: services/content/index.md
    - Scrapers: services/scrapers/index.md
    - Downloaders: services/downloaders/index.md
  - Ranking: https://dreulavelle.github.io/rank-torrent-name/users/faq/
  - Contributing: contribute.md

plugins:
  - search

theme:
  name: 'material'
  custom_dir: overrides
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.tracking
      - navigation.instant
      - navigation.instant.progress
      - navigation.sections
      - navigation.indexes
      - navigation.top
      - navigation.pruning
      - navigation.path
      - search.suggest
      - search.share
      - content.code.annotate
      - content.code.copy
      - announce.dismiss
      # - content.action.edit
  icon:
    logo: github
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Follow system preferences

  # font:
  #   text: 'Ubuntu'
  #   code: 'Ubuntu Mono'

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

extra:
  social:
    - icon: 'fontawesome/brands/discord'
      link: 'https://discord.gg/rivenmedia' 
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/rivenmedia/riven'
    - icon: 'fontawesome/solid/heart'
      link: 'https://github.com/sponsors/rivenmedia'
      text: 'Sponsor us on GitHub'

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - codehilite:
      linenums: false
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.superfences: