name: Notify Discord

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Notify Discord
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: "5373985"
          username: "Riven Media"
          avatar_url: "https://raw.githubusercontent.com/rivenmedia/wiki/refs/heads/main/images/image.png"
          # content: "||@everyone||"
          footer_title: "Wiki Update!"
          footer_icon_url: "https://raw.githubusercontent.com/rivenmedia/wiki/refs/heads/main/images/image.png"
          footer_timestamp: true