name: Update Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            overrides

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install poetry mkdocs-material

      - name: Cache MkDocs Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .cache
          key: rivenmedia-docs-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            rivenmedia-docs-${{ runner.os }}-

      - name: Build and Deploy MkDocs
        env:
          DEPLOY_BRANCH: gh-pages
        run: |
          poetry run mkdocs build
          poetry run mkdocs gh-deploy --force