name: Update Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Specify Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Cache MkDocs Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .cache
          key: mkdocs-material-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            mkdocs-material-${{ runner.os }}-

      - name: Build and Deploy MkDocs
        env:
          DEPLOY_BRANCH: gh-pages
        run: |
          poetry run mkdocs build
          poetry run mkdocs gh-deploy --force